export default [
    {
    "id": "q1",
    "title": "Quiz 1",
    "instructions": "Instruction",
    "quizType": "Practice Quiz",
    "points": 4,
    "assignmentGroup": "Quizzes",
    "status": false,
    "shuffleAnswers": true,
    "timeLimit": "10 Minutes",
    "multipleAttempts": false,
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "due": "2024-04-27",
    "availableDate": "2024-04-15",
    "untilDate": "2024-04-27",
    "course": "RS101",
    "__v": 0,
    "accessCode": "abcd",
    "showCorrectAnswers": "Immediately"
},
{
        "id": "q2",

    "title": "Quiz 2",
    "instructions": "Instruction",
    "quizType": "Practice Quiz",
    "points": 4,
    "assignmentGroup": "Quizzes",
    "status": false,
    "shuffleAnswers": true,
    "timeLimit": "10 Minutes",
    "multipleAttempts": false,
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "due": "2024-05-04",
    "availableDate": "2024-04-22",
    "untilDate": "2024-05-04",
    "course": "RS101",
    "__v": 0,
    "accessCode": "abcd",
    "showCorrectAnswers": "Immediately"
},
{
        "id": "q3",

    "title": "Quiz 3",
    "instructions": "Instruction",
    "quizType": "Practice Quiz",
    "points": 4,
    "assignmentGroup": "Quizzes",
    "status": false,
    "shuffleAnswers": true,
    "timeLimit": "10 Minutes",
    "multipleAttempts": false,
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "due": "2024-05-11",
    "availableDate": "2024-04-29",
    "untilDate": "2024-05-11",
    "course": "RS101",
    "__v": 0,
    "accessCode": "abcd",
    "showCorrectAnswers": "Immediately"
},
{
        "id": "q4",

    "title": "Quiz 4",
    "instructions": "Instruction",
    "quizType": "Practice Quiz",
    "points": 4,
    "assignmentGroup": "Quizzes",
    "status": false,
    "shuffleAnswers": true,
    "timeLimit": "10 Minutes",
    "multipleAttempts": false,
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "due": "2024-05-18",
    "availableDate": "2024-05-06",
    "untilDate": "2024-05-18",
    "course": "RS101",
    "__v": 0,
    "accessCode": "abcd",
    "showCorrectAnswers": "Immediately"
},
{
        "id": "q5",

    "title": "Quiz 5",
    "instructions": "Instruction",
    "quizType": "Practice Quiz",
    "points": 4,
    "assignmentGroup": "Quizzes",
    "status": false,
    "shuffleAnswers": true,
    "timeLimit": "10 Minutes",
    "multipleAttempts": false,
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "due": "2024-05-25",
    "availableDate": "2024-05-13",
    "untilDate": "2024-05-25",
    "course": "RS101",
    "__v": 0,
    "accessCode": "abcd",
    "showCorrectAnswers": "Immediately"
}


]